#!/bin/sh
NOTESTS=""
case $1 in
	notests)
		NOTESTS="-Dmaven.test.skip=true"
esac
# keystore needed for private email server
KEYSTORE="-Djavax.net.ssl.trustStore=$HOME/truststore"
LOGS=$HOME/logs
mkdir -p $LOGS
cd $HOME/projects/BIRT-Report-Runner-REST-Service
mvn $NOTESTS $KEYSTORE clean package > $LOGS/build-ms.log 2> $LOGS/build-ms.err.log
FAILURE_MESSAGE="$(grep "\[INFO\] BUILD FAILURE" $LOGS/build-ms.log)"
if [ -z "$FAILURE_MESSAGE" ]; then
	echo "succeeded"
	mkdir -p docs
	mv target/generated-docs/rest-api.html docs
else
	echo "failed"
fi
[ -z "$FAILURE_MESSAGE" ]