#!/bin/sh
# LIB=/disk1/home/innovent/OJC/lib
# for open source BIRT 4.8 use the com.innoventsolutions.birt.runtime public maven repo instead of this
LIB=$1
# echo "" > ./mvn-dependencies.xml
find $LIB -name "*.jar" -exec ./mvn-install-birt-jar "{}" \;
